// frontend/blurhash-react-project/src/App.tsx
import React from 'react';
import { useEffect } from 'react'
import './App.css'
import axios from 'axios'
import { useState } from 'react';
import { OptimizedImage } from './components/optimizedImage';
import { ApiData } from './models';

const apiUrl = "https://localhost:5001/api/Images";

function App() {
  const [apiData, setApiData] = useState<ApiData | null>(null);

  useEffect(() => {

    const fetchData = async () => {
      try {
        const response = await axios.get<ApiData>(apiUrl);
        setApiData(response.data);
      } catch (error) {
        console.error('Error fetching data:', error);
      }
    };

    fetchData();
  }, [])

  return (
    <>
      {apiData ? (
        apiData.uploadedImages.length ? (
          <div className="columns-2 md:columns-4 gap-4 space-y-4 p-4">
                {apiData.uploadedImages.map((item) => (
                  <div key={item.id}>
                    <OptimizedImage image={item} />
                  </div>
                ))}
          </div>
        ) :
        (
          <div className="flex items-center justify-center text-center text-lg">No data</div>
        )
      )
      : (
        <div className="flex items-center justify-center text-center text-lg">Loading...</div>
      )}
    </>
  )
}

export default App

// frontend/blurhash-angular-project/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiData } from 'src/models/models';

const apiUrl = "https://localhost:5001/api/Images";

type LoadingState = "Loading" | "Loaded" | "Error";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'blurhash-angular-project';
  error = null;
  status: LoadingState = "Loading";
  apiData: ApiData = {
    uploadedImages: [],
    uploadedImagesCount: 0
  }

  constructor(private httpClient: HttpClient) {
  }
  
  ngOnInit(){
    return this.httpClient.get<ApiData>(apiUrl)
    .subscribe({
      next: (response) => {
        this.apiData = response;
        this.status = 'Loaded';
      },
      error: (err) => {
        this.error = err;
        this.status = 'Error';
      },
    });
  }
}
<ng-container [ngSwitch]="status">
  <div *ngSwitchDefault class="flex items-center justify-center text-center text-lg">Loading...</div>
  
  <ng-container *ngSwitchCase="'Error'">
    <div *ngSwitchDefault class="flex items-center justify-center text-center text-lg">Something went wrong, please try again </div>
  </ng-container>

  <ng-container *ngSwitchCase="'Loaded'">
    <ng-template #noData>
      <div class="flex items-center justify-center text-center text-lg">No data</div>
    </ng-template>
    
    <div class="columns-2 md:columns-4 gap-4 space-y-4 p-4" *ngIf="apiData.uploadedImages.length;else noData">
      <div class="w-full h-full" *ngFor="let item of apiData.uploadedImages">
        <ngx-blurhash-render
          [blurHash]="item.blurHash"
          [imageSrc]="item.url"
          [width]="'100%'"
          [height]="'100%'"
          [borderRadius]="'12px'"
        >
        </ngx-blurhash-render>
      </div>
    </div>
  </ng-container>
</ng-container>
